// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCgb-nEp1D8ptA1vRPGrJWBQXnrll4dJw',
    appId: '1:1028746978784:web:5e632f925cf385457f7785',
    messagingSenderId: '1028746978784',
    projectId: 'medone-d8cbc',
    authDomain: 'medone-d8cbc.firebaseapp.com',
    storageBucket: 'medone-d8cbc.firebasestorage.app',
    measurementId: 'G-X60NDR81Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTNc3phv46nNYgjYdpdEu1l6Z8vSAgsI',
    appId: '1:1028746978784:android:cd46787c1f9753697f7785',
    messagingSenderId: '1028746978784',
    projectId: 'medone-d8cbc',
    storageBucket: 'medone-d8cbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXnDwWUqWudLPy_3ZGqet6JY9YMOMNNQ',
    appId: '1:1028746978784:ios:b68fc093b4246c6b7f7785',
    messagingSenderId: '1028746978784',
    projectId: 'medone-d8cbc',
    storageBucket: 'medone-d8cbc.firebasestorage.app',
    iosBundleId: 'com.example.medOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmXnDwWUqWudLPy_3ZGqet6JY9YMOMNNQ',
    appId: '1:1028746978784:ios:b68fc093b4246c6b7f7785',
    messagingSenderId: '1028746978784',
    projectId: 'medone-d8cbc',
    storageBucket: 'medone-d8cbc.firebasestorage.app',
    iosBundleId: 'com.example.medOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCgb-nEp1D8ptA1vRPGrJWBQXnrll4dJw',
    appId: '1:1028746978784:web:5c51d7b834a6cdf37f7785',
    messagingSenderId: '1028746978784',
    projectId: 'medone-d8cbc',
    authDomain: 'medone-d8cbc.firebaseapp.com',
    storageBucket: 'medone-d8cbc.firebasestorage.app',
    measurementId: 'G-C2EX3R3Q6D',
  );
}
